services:
  postgres:
    image: postgres:latest
    container_name: movie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_manager_db
    ports:
      - "5433:5432" # внешний порт 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: movie_redis
    restart: unless-stopped
    ports:
      - "6380:6379" # внешний порт 6380

volumes:
  pgdata:
